const productsData = [
  {
    id: 1,
    title: "Mocking Bird Guitar, 38inch Acoustic Guitar with Highly...",
    color: "Black",
    mrp: 9999,
    sp: 3299,
    img: "proImg01",
    rating: 4.5,
    num_reviews: 120,
  },
  {
    id: 2,
    title: "2Mocking Bird Guitar, 38inch Acoustic Guitar with Highly...",
    color: "Red",
    mrp: 23800,
    sp: 23299,
    img: "proImg02",
    rating: 3.0,
    num_reviews: 20,
  },
  {
    id: 3,
    title: "Another Guitar, 40inch Acoustic Guitar with...",
    color: "Brown",
    mrp: 2999,
    sp: 999,
    img: "proImg03",
    rating: 2.2,
    num_reviews: 85,
  },
  {
    id: 4,
    title: "Classic Acoustic Guitar, 41inch Full-Size Guitar...",
    color: "Tan",
    mrp: 12000,
    sp: 8999,
    img: "proImg04",
    rating: 4.8,
    num_reviews: 200,
  },
  {
    id: 5,
    title: "Electric Guitar, Solid Body, Vintage Sunburst Finish...",
    color: "Brown",
    mrp: 17999,
    sp: 14999,
    img: "proImg03",
    rating: 2.0,
    num_reviews: 50,
  },
  {
    id: 6,
    title: "Bass Guitar, 4-String Electric Bass, Metallic Blue...",
    color: "Tan",
    mrp: 15999,
    sp: 12999,
    img: "proImg04",
    rating: 4.6,
    num_reviews: 90,
  },
  {
    id: 7,
    title: "Acoustic-Electric Cutaway Guitar, Spruce Top, Black...",
    color: "Black",
    mrp: 14999,
    sp: 11999,
    img: "proImg01",
    rating: 3.3,
    num_reviews: 75,
  },
  {
    id: 8,
    title: "Beginner's Ukulele, Soprano Size, Mahogany Wood...",
    color: "Red",
    mrp: 4999,
    sp: 3499,
    img: "proImg02",
    rating: 1.9,
    num_reviews: 180,
  },
  {
    id: 9,
    title: "Kids' Guitar, 30inch Half-Size Acoustic Guitar, Blue...",
    color: "Black",
    mrp: 6999,
    sp: 4999,
    img: "proImg01",
    rating: 4.7,
    num_reviews: 150,
  },
  {
    id: 10,
    title: "New Guitar Model, 36inch Acoustic Guitar with...",
    color: "Red",
    mrp: 12000,
    sp: 8999,
    img: "proImg02",
    rating: 3.7,
    num_reviews: 150,
  },
];

export { productsData };
